import type { Category } from "./types.js";

export const fallbackMarketPreviews = [
  {
    id: "wc-england-score-both-halves-drc",
    category: "Sports" as Exclude<Category, "All">,
    timeframe: "Daily" as const,
    question: "Will England score in both halves against DR Congo?",
    probability: 48,
    marketAddress: "0x226BfF2b5A5e4F5686cfB37FaD7Dd345CfD68e01",
    deploymentBlock: 49623934,
    kickoffAt: "2026-07-01T16:00:00Z",
    expectedEndAt: "2026-07-01T17:45:00Z",
    resolveAfter: "2026-07-01T17:50:00Z",
    closes: "Jul 1, 4:40 PM GMT+1",
    resolution: "Resolves Yes if England are officially credited with at least one goal in the first half and at least one goal in the second half against DR Congo in their July 1, 2026 World Cup knockout match. Extra-time goals and penalty shootout goals do not count. Own goals count only if the official match record credits the goal to England's score in that half. Otherwise resolves No. Expected regulation end is 6:45 PM GMT+1; resolve a few minutes after the official match stats are final.",
    threadTopic: "England DR Congo World Cup Knockout",
    threadStoryId: 0,
    updates: 0,
    movement: 0,
    volume: "$0",
    traders: "0",
    liquidity: "$0",
    imageUrl: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=1200&q=80",
    evidence: []
  },
  {
    id: "wc-de-bruyne-score-assist-senegal",
    category: "Sports" as Exclude<Category, "All">,
    timeframe: "Daily" as const,
    question: "Will Kevin De Bruyne score or assist against Senegal?",
    probability: 44,
    marketAddress: "0x3603A839044Cc187A5B564C1b413BB764E8dA4E1",
    deploymentBlock: 49623934,
    kickoffAt: "2026-07-01T20:00:00Z",
    expectedEndAt: "2026-07-01T21:45:00Z",
    resolveAfter: "2026-07-01T21:50:00Z",
    closes: "Jul 1, 8:40 PM GMT+1",
    resolution: "Resolves Yes if Kevin De Bruyne is officially credited with at least one goal or at least one assist for Belgium against Senegal in their July 1, 2026 World Cup knockout match, including regular time and extra time. Penalty shootout goals do not count. If he does not play or is not officially credited with a goal or assist, resolves No. Expected regulation end is 10:45 PM GMT+1; resolve a few minutes after the official match stats are final.",
    threadTopic: "Belgium Senegal World Cup Knockout",
    threadStoryId: 0,
    updates: 0,
    movement: 0,
    volume: "$0",
    traders: "0",
    liquidity: "$0",
    imageUrl: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=1200&q=80",
    evidence: []
  },
  {
    id: "wc-usa-score-before-20-bosnia",
    category: "Sports" as Exclude<Category, "All">,
    timeframe: "Daily" as const,
    question: "Will the United States score before the 20th minute against Bosnia?",
    probability: 34,
    marketAddress: "0x1B890c4F066BC260cE3F0a8266303052080a0FB4",
    deploymentBlock: 49623934,
    kickoffAt: "2026-07-02T00:00:00Z",
    expectedEndAt: "2026-07-02T01:45:00Z",
    resolveAfter: "2026-07-02T01:50:00Z",
    closes: "Jul 2, 12:40 AM GMT+1",
    resolution: "Resolves Yes if the United States are officially credited with a goal before the match clock reaches 20:00 against Bosnia and Herzegovina in their July 1, 2026 World Cup knockout match. Own goals count only if the official match record adds the goal to the United States score before 20:00. Extra-time and penalty shootout goals do not count. Otherwise resolves No. This can be resolved after the 20th minute if Yes occurs, or after the match if No is confirmed.",
    threadTopic: "United States Bosnia World Cup Knockout",
    threadStoryId: 0,
    updates: 0,
    movement: 0,
    volume: "$0",
    traders: "0",
    liquidity: "$0",
    imageUrl: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?auto=format&fit=crop&w=1200&q=80",
    evidence: []
  },
  {
    id: "transfer-tonali-spurs",
    category: "Sports" as Exclude<Category, "All">,
    timeframe: "Sagas" as const,
    question: "Will Sandro Tonali sign with Tottenham Hotspur in the Summer Transfer Window?",
    probability: 58,
    closes: "September 1, 2026",
    resolution: "Resolves Yes if Tottenham Hotspur officially announces the transfer/signing of Sandro Tonali by the transfer deadline.",
    threadTopic: "Sandro Tonali Tottenham Transfer Link",
    threadStoryId: 0,
    updates: 0,
    movement: 0,
    volume: "$182K",
    traders: "980",
    liquidity: "$29K",
    imageUrl: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?auto=format&fit=crop&w=1200&q=80",
    evidence: []
  },
  {
    id: "transfer-guimaraes-arsenal",
    category: "Sports" as Exclude<Category, "All">,
    timeframe: "Sagas" as const,
    question: "Will Bruno Guimaraes officially sign with Arsenal by September 1, 2026?",
    probability: 45,
    closes: "September 1, 2026",
    resolution: "Resolves Yes if Arsenal officially announces the transfer/signing of Bruno Guimaraes by the transfer deadline.",
    threadTopic: "Bruno Guimaraes Arsenal Transfer Link",
    threadStoryId: 0,
    updates: 0,
    movement: 0,
    volume: "$204K",
    traders: "1,240",
    liquidity: "$36K",
    imageUrl: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=1200&q=80",
    evidence: []
  }
];
