import type { Category } from "./types.js";

const sports = "Sports" as Exclude<Category, "All">;

export const fallbackMarketPreviews = [
  {
    id: "wc-vozinha-saves-argentina",
    category: sports,
    timeframe: "Daily" as const,
    optionMarket: true,
    question: "What will Vozinha's official save total be against Argentina?",
    options: [
      { id: "under-4", label: "Under 4 saves" },
      { id: "exactly-4", label: "Exactly 4 saves" },
      { id: "exactly-5", label: "Exactly 5 saves" },
      { id: "six-plus", label: "6+ saves" }
    ],
    probability: 0,
    kickoffAt: "2026-07-03T22:00:00Z",
    closes: "Jul 3, 10:40 PM GMT+1",
    resolution: "One option resolves correct based on Vozinha's official save total for Cape Verde against Argentina in regular time and extra time. Penalty shootout saves do not count.",
    threadTopic: "Vozinha Argentina Save Watch",
    threadStoryId: 0,
    updates: 0,
    movement: 0,
    volume: "$0",
    traders: "0",
    liquidity: "$0",
    imageUrl: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=1200&q=80",
    evidence: []
  },
  {
    id: "wc-messi-impact-cape-verde",
    category: sports,
    timeframe: "Daily" as const,
    optionMarket: true,
    question: "How will Messi impact Cape Verde?",
    options: [
      { id: "scores-only", label: "Scores only" },
      { id: "assists-only", label: "Assists only" },
      { id: "score-and-assist", label: "Scores and assists" },
      { id: "no-goal-assist", label: "No goal or assist" }
    ],
    probability: 0,
    kickoffAt: "2026-07-03T22:00:00Z",
    closes: "Jul 3, 10:40 PM GMT+1",
    resolution: "One option resolves correct from Messi's official goal and assist record against Cape Verde, including regular time and extra time. Penalty shootout goals do not count.",
    threadTopic: "Messi Cape Verde Impact",
    threadStoryId: 0,
    updates: 0,
    movement: 0,
    volume: "$0",
    traders: "0",
    liquidity: "$0",
    imageUrl: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?auto=format&fit=crop&w=1200&q=80",
    evidence: []
  },
  {
    id: "wc-australia-egypt-first-event",
    category: sports,
    timeframe: "Daily" as const,
    optionMarket: true,
    question: "What happens first in Australia vs Egypt?",
    options: [
      { id: "salah-shot", label: "Salah shot on target" },
      { id: "australia-shot", label: "Australia shot on target" },
      { id: "yellow-card", label: "Yellow card" },
      { id: "goal", label: "Goal" }
    ],
    probability: 0,
    kickoffAt: "2026-07-03T18:00:00Z",
    closes: "Jul 3, 6:40 PM GMT+1",
    resolution: "One option resolves correct based on which listed event occurs first in official match order. If an unlisted event happens first, ignore it and continue until one listed event occurs.",
    threadTopic: "Australia Egypt First Event",
    threadStoryId: 0,
    updates: 0,
    movement: 0,
    volume: "$0",
    traders: "0",
    liquidity: "$0",
    imageUrl: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=1200&q=80",
    evidence: []
  },
  {
    id: "wc-colombia-ghana-halftime",
    category: sports,
    timeframe: "Daily" as const,
    optionMarket: true,
    question: "How does Colombia vs Ghana reach halftime?",
    options: [
      { id: "colombia-leading", label: "Colombia leading" },
      { id: "ghana-leading", label: "Ghana leading" },
      { id: "level-with-goals", label: "Level with goals" },
      { id: "nil-nil", label: "0-0" }
    ],
    probability: 0,
    kickoffAt: "2026-07-04T00:30:00Z",
    closes: "Jul 4, 1:10 AM GMT+1",
    resolution: "One option resolves correct based on the official halftime score after first-half stoppage time. Extra time and penalties are not relevant.",
    threadTopic: "Colombia Ghana Halftime Script",
    threadStoryId: 0,
    updates: 0,
    movement: 0,
    volume: "$0",
    traders: "0",
    liquidity: "$0",
    imageUrl: "https://images.unsplash.com/photo-1551958219-acbc608c6377?auto=format&fit=crop&w=1200&q=80",
    evidence: []
  },
  {
    id: "transfer-tonali-spurs",
    category: sports,
    timeframe: "Sagas" as const,
    question: "Will Sandro Tonali sign with Tottenham Hotspur in the Summer Transfer Window?",
    probability: 58,
    closes: "September 1, 2026",
    resolution: "Resolves Yes if Tottenham Hotspur officially announces the transfer/signing of Sandro Tonali by the transfer deadline.",
    threadTopic: "Sandro Tonali Tottenham Transfer Link",
    threadStoryId: 0,
    updates: 0,
    movement: 0,
    volume: "$182K",
    traders: "980",
    liquidity: "$29K",
    imageUrl: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?auto=format&fit=crop&w=1200&q=80",
    evidence: []
  },
  {
    id: "transfer-guimaraes-arsenal",
    category: sports,
    timeframe: "Sagas" as const,
    question: "Will Bruno Guimaraes officially sign with Arsenal by September 1, 2026?",
    probability: 45,
    closes: "September 1, 2026",
    resolution: "Resolves Yes if Arsenal officially announces the transfer/signing of Bruno Guimaraes by the transfer deadline.",
    threadTopic: "Bruno Guimaraes Arsenal Transfer Link",
    threadStoryId: 0,
    updates: 0,
    movement: 0,
    volume: "$204K",
    traders: "1,240",
    liquidity: "$36K",
    imageUrl: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=1200&q=80",
    evidence: []
  }
];
