import type { Category } from "./types.js";

const sports = "Sports" as Exclude<Category, "All">;

export const fallbackMarketPreviews = [
  {
    id: "wc-portugal-spain-qualify",
    category: sports,
    timeframe: "Daily" as const,
    optionMarket: true,
    question: "Which team will qualify in Portugal vs Spain?",
    options: [
      { id: "portugal", label: "Portugal" },
      { id: "spain", label: "Spain" }
    ],
    probability: 0,
    kickoffAt: "2026-07-06T19:00:00Z",
    closes: "Jul 6, 7:40 PM GMT+1",
    resolution: "One option resolves correct based on the team that officially qualifies in Portugal vs Spain, including extra time and penalties.",
    threadTopic: "Portugal vs Spain Qualify Watch",
    threadStoryId: 0,
    updates: 0,
    movement: 0,
    volume: "$0",
    traders: "0",
    liquidity: "$0",
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=1200&q=80",
    evidence: []
  },
  {
    id: "wc-ronaldo-header-spain",
    category: sports,
    timeframe: "Daily" as const,
    optionMarket: true,
    question: "Will Cristiano Ronaldo score a header vs Spain?",
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No" }
    ],
    probability: 0,
    kickoffAt: "2026-07-06T19:00:00Z",
    closes: "Jul 6, 7:40 PM GMT+1",
    resolution: "Resolves Yes if Cristiano Ronaldo is officially credited with a headed goal for Portugal against Spain in regular time or extra time. Penalty shootout goals do not count. Otherwise resolves No.",
    threadTopic: "Ronaldo Header Watch vs Spain",
    threadStoryId: 0,
    updates: 0,
    movement: 0,
    volume: "$0",
    traders: "0",
    liquidity: "$0",
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=1200&q=80",
    evidence: []
  },
  {
    id: "wc-usa-belgium-qualify",
    category: sports,
    timeframe: "Daily" as const,
    optionMarket: true,
    question: "Which team will qualify in USA vs Belgium?",
    options: [
      { id: "usa", label: "USA" },
      { id: "belgium", label: "Belgium" }
    ],
    probability: 0,
    kickoffAt: "2026-07-07T00:00:00Z",
    closes: "Jul 7, 12:40 AM GMT+1",
    resolution: "One option resolves correct based on the team that officially qualifies in USA vs Belgium, including extra time and penalties.",
    threadTopic: "USA vs Belgium Qualify Watch",
    threadStoryId: 0,
    updates: 0,
    movement: 0,
    volume: "$0",
    traders: "0",
    liquidity: "$0",
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=1200&q=80",
    evidence: []
  },
  {
    id: "wc-usa-goals-belgium",
    category: sports,
    timeframe: "Daily" as const,
    optionMarket: true,
    question: "How many goals will USA score in regular + extra time vs Belgium?",
    options: [
      { id: "0", label: "0 goals" },
      { id: "1", label: "1 goal" },
      { id: "2", label: "2 goals" },
      { id: "3-plus", label: "3+ goals" }
    ],
    probability: 0,
    kickoffAt: "2026-07-07T00:00:00Z",
    closes: "Jul 7, 12:40 AM GMT+1",
    resolution: "One option resolves correct based on the number of goals officially scored by the United States against Belgium in regular time and extra time. Penalty shootout goals do not count.",
    threadTopic: "USA Goals vs Belgium",
    threadStoryId: 0,
    updates: 0,
    movement: 0,
    volume: "$0",
    traders: "0",
    liquidity: "$0",
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=1200&q=80",
    evidence: []
  },
  {
    id: "transfer-tonali-spurs",
    category: sports,
    timeframe: "Sagas" as const,
    question: "Will Sandro Tonali sign with Tottenham Hotspur in the Summer Transfer Window?",
    probability: 58,
    closes: "September 1, 2026",
    resolution: "Resolves Yes if Tottenham Hotspur officially announces the transfer/signing of Sandro Tonali by the transfer deadline.",
    threadTopic: "Sandro Tonali Tottenham Transfer Link",
    threadStoryId: 0,
    updates: 0,
    movement: 0,
    volume: "$182K",
    traders: "980",
    liquidity: "$29K",
    imageUrl: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?auto=format&fit=crop&w=1200&q=80",
    evidence: []
  },
  {
    id: "transfer-guimaraes-arsenal",
    category: sports,
    timeframe: "Sagas" as const,
    question: "Will Bruno Guimaraes officially sign with Arsenal by September 1, 2026?",
    probability: 45,
    closes: "September 1, 2026",
    resolution: "Resolves Yes if Arsenal officially announces the transfer/signing of Bruno Guimaraes by the transfer deadline.",
    threadTopic: "Bruno Guimaraes Arsenal Transfer Link",
    threadStoryId: 0,
    updates: 0,
    movement: 0,
    volume: "$204K",
    traders: "1,240",
    liquidity: "$36K",
    imageUrl: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=1200&q=80",
    evidence: []
  }
];
