import { categories, mockStories } from "./mockNews.js";
import type { ArchiveDate, Category, NewsStory } from "./types.js";

const state: {
  activeCategory: Category;
  stories: NewsStory[];
  isLoading: boolean;
  selectedStoryId: number | null;
  aiSummaries: Record<string, string>;
  loadingSummaryUrl: string | null;
  archiveDates: ArchiveDate[];
  activeArchiveDate: string | null;
} = {
  activeCategory: "All",
  stories: mockStories,
  isLoading: false,
  selectedStoryId: null,
  aiSummaries: {},
  loadingSummaryUrl: null,
  archiveDates: [],
  activeArchiveDate: null
};

const dateLabel = document.querySelector<HTMLParagraphElement>("#dateLabel");
const categoryTabs = document.querySelector<HTMLElement>("#categoryTabs");
const storyList = document.querySelector<HTMLElement>("#storyList");
const storyDetail = document.querySelector<HTMLElement>("#storyDetail");
const menuButton = document.querySelector<HTMLButtonElement>("#menuButton");
const menuPanel = document.querySelector<HTMLElement>("#menuPanel");
const menuStatus = document.querySelector<HTMLParagraphElement>("#menuStatus");
const archiveDateSelect = document.querySelector<HTMLSelectElement>("#archiveDateSelect");
const archiveStatus = document.querySelector<HTMLSpanElement>("#archiveStatus");
const todayButton = document.querySelector<HTMLButtonElement>("#todayButton");

const getFilteredStories = (): NewsStory[] =>
  state.stories.filter((story) => state.activeCategory === "All" || story.category === state.activeCategory);

const cleanSummaryText = (value: string): string => {
  let summary = String(value || "").trim();

  for (let attempt = 0; attempt < 2; attempt += 1) {
    const fenced = summary.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/i);
    if (fenced) summary = fenced[1].trim();

    if (!/^\s*\{[\s\S]*\}\s*$/.test(summary)) break;

    try {
      const parsed = JSON.parse(summary);
      if (typeof parsed.summary === "string") {
        summary = parsed.summary.trim();
        continue;
      }
    } catch {
      break;
    }

    break;
  }

  return summary
    .replace(/^["'{\s]+/, "")
    .replace(/["'}\s]+$/, "")
    .replace(/^summary\s*:\s*/i, "")
    .replace(/\s+/g, " ")
    .trim();
};

const loadStorySummary = async (story: NewsStory): Promise<void> => {
  if (state.aiSummaries[story.sourceUrl] || state.loadingSummaryUrl === story.sourceUrl) return;

  if (story.ai_summary) {
    state.aiSummaries[story.sourceUrl] = cleanSummaryText(story.ai_summary);
    if (menuStatus) {
      menuStatus.textContent = story.ai_provider === "0g" ? "Archived 0G summary loaded" : "Archived summary loaded";
    }
    renderDetail();
    return;
  }

  state.loadingSummaryUrl = story.sourceUrl;
  renderDetail();

  try {
    const response = await fetch("/api/summary", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(story)
    });

    if (!response.ok) {
      throw new Error(`Summary request failed with ${response.status}`);
    }

    const data = await response.json();
    state.aiSummaries[story.sourceUrl] = cleanSummaryText(data.summary || story.summary);
    if (menuStatus && data.provider) {
      menuStatus.textContent = data.provider === "0g" ? "Summary generated by 0G" : `Summary loaded from ${data.provider}`;
    }
  } catch (error) {
    console.warn(error);
    state.aiSummaries[story.sourceUrl] = cleanSummaryText(story.summary);
    if (menuStatus) {
      menuStatus.textContent = "Summary fallback loaded";
    }
  } finally {
    state.loadingSummaryUrl = null;
    renderDetail();
  }
};

const openStory = (storyId: number): void => {
  const story = state.stories.find((item) => item.id === storyId);
  if (!story) return;

  state.selectedStoryId = story.id;
  window.history.pushState({}, "", `#story-${story.id}`);
  render();
  void loadStorySummary(story);
  window.scrollTo({ top: 0, behavior: "smooth" });
};

const closeStory = (): void => {
  state.selectedStoryId = null;
  window.history.pushState({}, "", window.location.pathname);
  render();
};

const syncStoryFromHash = (): void => {
  const match = window.location.hash.match(/^#story-(\d+)$/);
  const story = match ? state.stories.find((item) => item.id === Number(match[1])) : undefined;
  state.selectedStoryId = story?.id ?? null;
  render();
  if (story) void loadStorySummary(story);
};

const setArchiveStatus = (message: string): void => {
  if (archiveStatus) archiveStatus.textContent = message;
};

const loadFeed = async (category: Category = state.activeCategory): Promise<void> => {
  state.isLoading = true;
  state.selectedStoryId = null;
  renderStories();

  try {
    const endpoint = state.activeArchiveDate
      ? `/api/archive?date=${encodeURIComponent(state.activeArchiveDate)}&category=${encodeURIComponent(category)}`
      : `/api/feed?category=${encodeURIComponent(category)}`;
    const response = await fetch(endpoint);
    if (!response.ok) throw new Error(`Feed request failed with ${response.status}`);

    const data = await response.json();
    state.stories = data.top_stories ?? mockStories;
    if (menuStatus) {
      if (state.activeArchiveDate) {
        menuStatus.textContent = `Showing ${category} from ${state.activeArchiveDate}`;
      } else {
        const archiveLabel = data.archive?.provider === "shelby" ? "Shelby" : "local archive";
        menuStatus.textContent = `Latest published feed loaded from ${archiveLabel}`;
      }
    }
    setArchiveStatus(state.activeArchiveDate ? `Archive: ${state.activeArchiveDate}` : "Live feed");
  } catch (error) {
    console.warn(error);
    state.stories = mockStories;
    if (menuStatus) {
      menuStatus.textContent = state.activeArchiveDate
        ? "That saved day/category is not available yet"
        : "Using mock feed until sources are configured";
    }
  } finally {
    state.isLoading = false;
    render();
    syncStoryFromHash();
  }
};

const loadArchiveIndex = async (): Promise<void> => {
  if (!archiveDateSelect) return;

  try {
    const response = await fetch("/api/archive");
    if (!response.ok) throw new Error(`Archive index failed with ${response.status}`);

    const data = await response.json();
    state.archiveDates = data.dates ?? [];
    archiveDateSelect.innerHTML = [
      `<option value="">Today</option>`,
      ...state.archiveDates.map((entry) => `<option value="${entry.date}">${entry.date}</option>`)
    ].join("");
    archiveDateSelect.value = state.activeArchiveDate ?? "";
    setArchiveStatus(state.archiveDates.length > 0 ? "Saved days ready" : "No saved days yet");
  } catch (error) {
    console.warn(error);
    setArchiveStatus("Archive unavailable");
  }
};

const renderCategories = (): void => {
  if (!categoryTabs) return;

  categoryTabs.innerHTML = categories
    .map(
      (category) => `
        <button class="category-tab ${category === state.activeCategory ? "active" : ""}" type="button" data-category="${category}">
          ${category}
        </button>
      `
    )
    .join("");
};

const renderStories = (): void => {
  if (!storyList) return;

  const stories = getFilteredStories();
  storyList.hidden = Boolean(state.selectedStoryId);

  if (state.isLoading) {
    storyList.innerHTML = `
      <article class="story-card loading-card">
        <div class="story-copy">
          <span class="category-chip">Siftle</span>
          <h2>Gathering today's trending stories...</h2>
          <p>Pulling fresh sources and preparing the feed.</p>
        </div>
      </article>
    `;
    return;
  }

  if (stories.length === 0) {
    storyList.innerHTML = `<div class="empty-state">No briefs found for this view.</div>`;
    return;
  }

  storyList.innerHTML = stories
    .map(
      (story) => `
        <article class="story-card" data-story-id="${story.id}" role="button" tabindex="0" aria-label="Open summary for ${story.headline}">
          <div class="story-topline">
            <div class="story-source">
              <div class="story-icon ${story.accent}" aria-hidden="true">
                <span></span>
              </div>
              <div>
                <strong>${story.source}</strong>
                <span>${story.postedAt} ago - ${story.readTime}</span>
              </div>
            </div>
            <button class="save-button ${story.saved ? "saved" : ""}" type="button" aria-label="Save story" data-save-id="${story.id}">
              <span></span>
            </button>
          </div>

          <div class="story-image-frame" aria-hidden="true">
            <img src="${story.imageUrl}" alt="" loading="lazy" />
          </div>

          <div class="story-copy">
            <span class="category-chip ${story.category}">${story.category}</span>
            <h2>${story.headline}</h2>
            <p>Tap to read the AI summary.</p>
          </div>

          <div class="card-action-row">
            <a class="card-source-button" href="${story.sourceUrl}" target="_blank" rel="noreferrer">Open source</a>
          </div>
        </article>
      `
    )
    .join("");
};

const renderDetail = (): void => {
  if (!storyDetail || !storyList) return;

  const story = state.stories.find((item) => item.id === state.selectedStoryId);
  if (!story) {
    storyDetail.hidden = true;
    storyDetail.classList.remove("fullscreen");
    document.body.classList.remove("detail-mode");
    storyList.hidden = false;
    return;
  }

  const summary = cleanSummaryText(state.aiSummaries[story.sourceUrl] || story.summary);
  const isLoadingSummary = state.loadingSummaryUrl === story.sourceUrl;

  storyList.hidden = true;
  storyDetail.hidden = false;
  storyDetail.classList.add("fullscreen");
  document.body.classList.add("detail-mode");
  storyDetail.innerHTML = `
    <button class="back-button" type="button" data-back-to-feed>Back to feed</button>
    <article class="detail-card">
      <div class="detail-topline">
        <span class="category-chip ${story.category}">${story.category}</span>
        <span>${story.source} - ${story.postedAt} ago - ${story.readTime}</span>
      </div>
      <h2>${story.headline}</h2>
      <img class="detail-image" src="${story.imageUrl}" alt="" />
      <section class="detail-summary">
        <strong>AI summary</strong>
        <p>${isLoadingSummary ? "Preparing a short AI summary..." : summary}</p>
      </section>
      <a class="source-button" href="${story.sourceUrl}" target="_blank" rel="noreferrer">Open source</a>
    </article>
  `;
};

const render = (): void => {
  renderCategories();
  renderStories();
  renderDetail();
  if (archiveDateSelect) archiveDateSelect.value = state.activeArchiveDate ?? "";
};

dateLabel!.textContent = new Intl.DateTimeFormat("en", {
  month: "long",
  day: "numeric",
  year: "numeric"
}).format(new Date());

categoryTabs?.addEventListener("click", (event) => {
  const target = event.target as HTMLElement;
  const button = target.closest<HTMLButtonElement>("[data-category]");
  if (!button) return;

  state.activeCategory = button.dataset.category as Category;
  window.history.pushState({}, "", window.location.pathname);
  render();
  void loadFeed(state.activeCategory);
});

archiveDateSelect?.addEventListener("change", () => {
  state.activeArchiveDate = archiveDateSelect.value || null;
  window.history.pushState({}, "", window.location.pathname);
  render();
  void loadFeed(state.activeCategory);
});

todayButton?.addEventListener("click", () => {
  state.activeArchiveDate = null;
  if (archiveDateSelect) archiveDateSelect.value = "";
  window.history.pushState({}, "", window.location.pathname);
  render();
  void loadFeed(state.activeCategory);
});

storyList?.addEventListener("click", (event) => {
  const target = event.target as HTMLElement;
  const saveButton = target.closest<HTMLButtonElement>("[data-save-id]");
  const storyCard = target.closest<HTMLElement>("[data-story-id]");

  if (saveButton) {
    event.stopPropagation();
    const storyId = Number(saveButton.dataset.saveId);
    state.stories = state.stories.map((story) =>
      story.id === storyId ? { ...story, saved: !story.saved } : story
    );
    renderStories();
    return;
  }

  if (!storyCard) return;
  if (target.closest("a")) return;
  openStory(Number(storyCard.dataset.storyId));
});

storyList?.addEventListener("keydown", (event) => {
  const target = event.target as HTMLElement;
  const storyCard = target.closest<HTMLElement>("[data-story-id]");
  if (!storyCard || (event.key !== "Enter" && event.key !== " ")) return;

  event.preventDefault();
  openStory(Number(storyCard.dataset.storyId));
});

storyDetail?.addEventListener("click", (event) => {
  const target = event.target as HTMLElement;
  const backButton = target.closest<HTMLButtonElement>("[data-back-to-feed]");
  if (backButton) closeStory();
});

window.addEventListener("popstate", syncStoryFromHash);

menuButton?.addEventListener("click", () => {
  if (!menuPanel || !menuButton) return;

  const isOpen = !menuPanel.hidden;
  menuPanel.hidden = isOpen;
  menuButton.setAttribute("aria-expanded", String(!isOpen));
});

document.addEventListener("click", (event) => {
  const target = event.target as HTMLElement;
  const button = target.closest<HTMLButtonElement>("[data-menu-action]");
  if (!button) return;

  const labels: Record<string, string> = {
    today: "Showing today's brief",
    saved: `${state.stories.filter((story) => story.saved).length} saved stories`,
    archive: state.archiveDates.length > 0 ? "Choose a saved day from the archive selector" : "No saved days yet"
  };
  if (menuStatus) menuStatus.textContent = labels[button.dataset.menuAction ?? "today"];
  if (button.dataset.menuAction === "today") {
    state.activeArchiveDate = null;
    if (archiveDateSelect) archiveDateSelect.value = "";
    void loadFeed(state.activeCategory);
  }
});

render();
void loadArchiveIndex();
void loadFeed();
